### ISSUE TITLE
Cancelling jobs with Ctrl+C

### ISSUE THREAD

**Issue by mschubert** [percyfal/slurm#7]
If I terminate my *snakemake* run using <kbd>Ctrl</kbd>+<kbd>c</kbd>, I get a message that jobs are being terminated:

```
Terminating processes on user request, this might take some time.
Will exit after finishing currently running jobs.
Complete log: .snakemake/log/2018-04-14T181905.465710.snakemake.log
>
```

However, the jobs are still listed in `squeue` and are still running after exiting.

Is this intentional?

I also sometimes instead of *job is being submitted* get a message that *job is resumed* and then they are never started (but I haven't found a way to reliably reproduce that)

**Comment by percyfal** [comment]
This is not intentional, but I haven't yet had time to fix it. The thread at https://bioinformatics.stackexchange.com/questions/491/how-are-snakemakes-cluster-and-drmaa-options-implemented describes a related issue. If still relevant, it depends on how snakemake submits jobs with the --profile flag. If it is similar to using --cluster, then it seems to be quite tricky to implement. I won't be able to look into this until next week, so if you do find a solution, I'd happily accept a pull request.

**Comment by mschubert** [comment]
If I understand correctly, for `--drmaa` I'd still have to provide a cluster configuration file at the command-line for every call to `snakemake` (because the scheduler needs some default options to be passed, e.g. runtime and memory).

In addition, I assumed that `--profile` would supersede `--cluster` (and `--drmaa`), but I might be mistaken.

(As for a PR, I'm sorry - this is quite unlikely due to time constraints.*But* I don't think it's that tricky, one could just use an `scancel` in a finalizer [as I did here](https://github.com/mschubert/clustermq/blob/master/R/qsys_slurm.r#L35) for an R package)
